### ISSUE TITLE
Getting multiple errors from appoptics which restarts the Node process

### ISSUE THREAD

**Issue by immohitrathi** [appoptics/appoptics-apm-node#134]
Below errors are getting logged in stdout at the same time when our Node process is getting restarted. At this point we're not sure if this is the main reason for process restarts or not. This is happening exactly after 12 hours at 11:30. 

Below is the alert which we get.
`Kubernetes POD Restart Alert: Namespace:: 99-discovery, Service:: discovery-99webreact, POD_Name:: discovery-99webreact-8467485d45-5gfqh has been restarted; restart-count:: 1, Reason: Completed, Exit-code: 0, Pod-Age: 7d, Worker-node: npl9dba10.ieil.net`

Please tell possible reasons for this.

1. [Fri Jan 15 06:00:05 2021] Failed to flush data before timeout of 5000 ms reached! [reporter/ssl.cc:2597] [AppOptics-SSL_reporter-error p#6.6]
2. [Fri Jan 15 06:00:40 2021] Send failed - reporter returned 65507 [oboe.c:690] [AppOptics-lib-error p#6.6]
3. 15-1-2021 6:0:0 :  caught uncaughtException : Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:406:19)
    at clearBuffer (_stream_writable.js:540:7)
    at onwrite (_stream_writable.js:465:7)
    at lazyFs.write (internal/fs/streams.js:304:5)
    at /opt/node_app/app/node_modules/appoptics-apm/lib/span.js:275:15
    at clsBind (/opt/node_app/app/node_modules/ace-context/context.js:263:17)
    at FSReqWrap.wrapper [as oncomplete] (fs.js:502:5)

**Comment by bmacnaughton** [comment]
@immohitrathi - can you provide specifics on the OS/version and agent/version? i am not familiar with kubernetes so this is mostly guesswork: the first two messages are because the agent couldn't communicate with the collector. maybe kubernetes has disabled communications before stopping processes/waiting for processes to stop? That would explain the issue with attempting to write to a stream once it's been destroyed as well.

The communications component of the agent is a c/c++ addon that attempts to flush any remaining data when the process is shutting down. The appoptics component in the stack trace (span.js) is not actually performing any io; it's just making a callback. the fs internal `lazyFs.write` hints that it might be a similar situation.

**Comment by immohitrathi** [comment]
Are you suggesting that these errors are side effects but not actual reasons for process exit?

**Comment by bmacnaughton** [comment]
the errors all could result from network connections disappearing (the node error definitely is - the stream is destroyed).

i don't see any errors that would have happened before network connections disappeared.

so, yes, they look like side effects of either the network disappearing/being shutdown before processes are terminated. the ERR_STREAM_DESTROYED error could cause the system to shutdown because it's an uncaught exception. but i can't tell from the trace. the span:275 call is just invoking a callback. and the instrumentation logic at no time performs any stream IO at this point, so it appears that the error is not a result of the instrumentation.

so it looks like the ERR_STREAM_DESTROYED is the reason for the process exit but the instrumentation doesn't attempt to write to the stream; it looks like a normal flow of control up until the fs internal functions detect that the stream is gone.

**Comment by bmacnaughton** [comment]
a coworker mentioned that this could be an aggressive firewall/proxy that is cleaning up long-lived open sockets (if it is recurring and is always 12 hours after the connection was established).

**Comment by bmacnaughton** [comment]
@immohitrathi - any additional information on this?

**Comment by bmacnaughton** [comment]
@immohitrathi - i'm going to close this. feel free to reopen if there is an issue we can look into.

in the meantime, `appoptics-apm@10.0.0` is ga and includes the fixes in the rc version you're using. it would be best to stop using the rc version as it was a bit pre-release and uses a pre-release version of @appoptics/apm-bindings that wasn't published to the production binaries area.
